### ISSUE TITLE
Why does `txtai` do over direct comparison of query & document embeddings?

### ISSUE THREAD

**Issue by ydennisy** [neuml/txtai#132]
hi @davidmezzetti 

Thanks for the great library!

I was doing a POC of a few different solutions:
- Facebook DPR
- Raw sentence transformers
- txtai

What I noticed is that when using raw transformers and just embedding all my docs, and the query - the results are (visually) worse that when using `txtai` - I had a little look over the code to see what else is being done, and saw some LSA or topic modelling, I cannot remember now... but anyway I would like to ask to see if you could outline what else is done apart from a direct embedding of doc & query and then cosine sim between the two vectors?

Thanks!
D

**Comment by davidmezzetti** [comment]
Thank you for the nice words.

In most cases, the functionality should mirror sentence-transformers. The main differences are:

1. (Most likely) The [vectors are normalized](https://github.com/neuml/txtai/blob/1d3d933e01c84329b40472d7a52c7986cc354a0e/src/python/txtai/embeddings/base.py#L412).
2. If tokenize is enabled in the embeddings settings (i.e.`Embeddings({"tokenize": True})`), [stop words are removed](https://github.com/neuml/txtai/blob/1d3d933e01c84329b40472d7a52c7986cc354a0e/src/python/txtai/vectors/transformers.py#L104) from the sentences before vector conversion
3. If PCA is enabled in the embeddings settings (i.e.`Embeddings({"pca": n})`), [n principal components are removed](https://github.com/neuml/txtai/blob/1d3d933e01c84329b40472d7a52c7986cc354a0e/src/python/txtai/embeddings/base.py#L79) from the vectors
4. When querying through Faiss, it's possible the approximate results look better than the full cosine similarity results

With 2 and 3, you would have had to enable those, so it's unlikely. Best guess is the difference you're seeing is due to normalization. Note that the sentence-transformers library does have an option to [normalize vectors](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L110) as well.

**Comment by ydennisy** [comment]
Thanks @davidmezzetti the biggest difference must be 1.

I must say I am surprised as I thought that normalising would "lose information".

Will run again with normalised and revert back.

**Comment by ydennisy** [comment]
@davidmezzetti I noticed I was always using cosine similarity anyway - so normalizing would not make any difference.

Could you elaborate on why point 3, could be of use in this setting?

**Comment by davidmezzetti** [comment]
Setting PCA for a transformers model wouldn't typically be appropriate. This setting has been in txtai since the beginning when it predominately worked with BM25 + fastText vectors. 

Would it be possible to distill down an example where txtai and sentence-transformers are producing different vectors for the same data?

**Comment by davidmezzetti** [comment]
Please feel free to re-open or open a new issue should you have further questions
