### ISSUE TITLE
HFOnnx expects ORT provider

### ISSUE THREAD

**Issue by chintanckg** [neuml/txtai#195]
```embeddings = onnx("sentence-transformers/paraphrase-MiniLM-L6-v2", "pooling", "embeddings.onnx", quantize=True)```

ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue! The problem comes in when onnxruntime-gpu is installed as that has multiple providers. Logic has been added to set providers based on the available providers. 

This will be available when 4.0 is released. It can also be [installed from source](https://neuml.github.io/txtai/install/#install-from-source) right now.

**Comment by chintanckg** [comment]
> Thank you for reporting this issue! The problem comes in when onnxruntime-gpu is installed as that has multiple providers. Logic has been added to set providers based on the available providers.
> 
> This will be available when 4.0 is released. It can also be [installed from source](https://neuml.github.io/txtai/install/#install-from-source) right now.

Thanks @davidmezzetti
