### ISSUE TITLE
Increamental Indexing

### ISSUE THREAD

**Issue by roy-sr** [neuml/txtai#251]
Is it possible to add new data in previously created index files ? E.g. If I have created and saved a Embedding Index file with 5K records and, after some days I have new 2K data which I want to include in my old index file then can I load the old index file and append the new 2K data into it so that when we query in the updated embedding index it will include the new 2K data too ?
OR I need to re-index the whole 7K (old 5k + new 2K) data together ?

**Comment by chang48** [comment]
An observation: I use the following code from one of the example notebook to generate a stream of data for indexing:
```
def stream(df, limit):
    index = 0
    for _, row in df.iterrows():
        token = {'text': row.desc,
                 'brand': row.brand,
                 ....
                }
        yield (index, token, None)
        index += 1

        if index >= limit:
            break
```

Let say I use the function to index the first 10 rows of df. Later on, index the next 10 rows. However, the sqlite db file `documents` only contains the last 10 instead of 20.

After checking the database file and the `stream` function, it occurs to me that the two streams have the same `index`. So while they have different `indexid`, their `id` are identical. Is this the reason why the data was overwritten instead of appended?

<img width="968" alt="Screen Shot 2022-07-07 at 2 53 11 PM" src="https://user-images.githubusercontent.com/2575869/177877955-2da1f721-e23d-442f-a9ac-6b1a16775b1e.png">

**Comment by chang48** [comment]
@davidmezzetti The hash id method works well for our project where we need to upset regularly. Thanks!

**Comment by davidmezzetti** [comment]
Happy to hear it!
