### ISSUE TITLE
Feature request: Bind variable support when searching with SQL using Content=True mode

### ISSUE THREAD

**Issue by rickknowles-cognitant** [neuml/txtai#564]
When doing SQL queries, it's considered good practice to support "?" or ":label" style bind args so that query parameters can't have SQL injection parameters supplied. 

SQLite supports this (as do most databases), but it appears the txtai wrapper around it doesn't pass this feature through.

Would it be possible to request this addition please ? It would make the difference between being able to use txtai in production environments and not in my case.

Thank you

**Comment by rickknowles-cognitant** [comment]
Sorry, updated just for clarification's sake: what I'm requesting here is the ability to do something like the following in Content=True mode:
```
embeddings.search("SELECT id, score FROM txtai WHERE flag=? OR category=?", 5, [1, 'dogs'])
```
or perhaps:
```
embeddings.search("SELECT id, score FROM txtai WHERE flag=:myflag OR category=:mycategory", 5, { myflag: 1, mycategory: 'dogs' })
```

and the main result would be confidence that someone passing in `{myCategory: "'; DROP TABLES xxx"}` would not result in a security problem

**Comment by davidmezzetti** [comment]
Thank you for this issue. It will be worked in an upcoming release.

txtai's SQL doesn't run at the native level. It's parsed and reconstructed using a fixed SQL statement. But I do think it's possible to pass bind variables down to the native SQL level.

Having bind parameters would enable passing non-text content to a similar clause as requested in #404.

**Comment by zaphoyd** [comment]
+1 on this and a bit more digging here:

The query you feed to `embeddings.search` doesn't appear to be passed directly to an RDBMS, so there is some existing protection against SQL injection. The query is parsed by a txtai preprocessor, taken apart, and then put back together (with proper escaping and parameterization). It is possible to inject stuff that confuses the txtai query preprocessor. This is a little less dangerous, but still can result in errors, DoS type issues, and generally the system not working the way the library user expects.

Right now, to mitigate this, the library user needs to implement an escaping system for the txtai preprocessor itself, at minimum to avoid users sending queries with quotes in them from failing. This involves some guesswork and/or library reverse engineering that feels like it ought to be handled by the underlying library.

In a Slack conversation David also noted, #404 , which is also limited by the text only transport for passing data to the underlying database. Making it easier to pass binary parameters would be nice.

Parameterized queries to `embeddings.search` that were carried through to the underlying RDBMS query would be a straightforward solution to a number of these issues. Because this query is sent to multiple different types of thing (read by txtai itself, sent to vector DBs, sent to multiple different RDBMSes) there might need to be multiple different types of escaping at different points in the process. Parameterization allows deferring escaping until the point where the library knows what escaping would be appropriate and allows passing parameters directly to underlying search systems that support parameterization.

**Comment by davidmezzetti** [comment]
A change just went in to add this functionality. It uses named parameters. Examples below.

```python
# Bind parameter with a similar() clause
embeddings.search("select id, text, score from txtai where similar(:x)", parameters={"x": "feel good story"})

# Bind parameter for binary content
embeddings.search("select id, text, score from txtai where similar(:x)", parameters={"x": Image.read(path)})

# Bind parameter with standard SQL
embeddings.search("select * from txtai where text like :x", parameters={"x": "%iceberg%"})
```

For similar clauses, the bind parameters are applied during the ANN lookup. Other bind parameters pass through to the native SQL engine (SQLite, DuckDB or SQLAlchemy). 

Note that DuckDB doesn't support named parameters and logic exists to convert named parameter SQL to question marks + a list of params.

This only works when `content=True` like SQL does currently. If a SQL statement is passed with `content=False` it will use the full input string as the text to search.
