### ISSUE TITLE
TXTAI for RAG and more? GUI Integration?

### ISSUE THREAD

**Issue by andykaufseo** [neuml/txtai#668]
I've been looking for a RAG setup for a while now and txtai seems to be the best option out there. however, i have a few questions

- is it possible to store all the data used (from the uploaded documents) in a database (embedding or vector) and use it continuously? i'm asking this because i have tried other similar systems, and whenever it got shut down, it forgot everything (database was deleted and i had to re-upload all the documents) - i'm looking to build a very large database of documents, and it will keep on growing

- is there any sort of GUI that can integrate with txtai and it's databases? something like oobabooga textgen webui or kobold / sillytavern or even txtchat?

- do you guys have a discord or any sort of chat channel? i bet thing thing is (or will be) used but tons of people, and chat room is definitely going to be really helpful for everyone

**Comment by davidmezzetti** [comment]
Hello, thank you for taking a look at txtai. Please see answers below.

- Yes, the idea of a txtai embeddings database is for long term storage. But you need to [save](https://neuml.github.io/txtai/embeddings/methods/#txtai.embeddings.Embeddings.save) it otherwise it will only be an in-memory database. Depending on how you run txtai, this may happen automatically.

- The idea of txtchat is to be a chat-based GUI. Given that txtai can run as an API service, I'm sure it can integrate with those other tools too, would just take some development work to do so.

- Link to [txtai's slack](https://join.slack.com/t/txtai/shared_invite/zt-1cagya4yf-DQeuZbd~aMwH5pckBU4vPg)

**Comment by andykaufseo** [comment]
alright, pretty cool, thanks for the help
