### ISSUE TITLE
Fix issue with hardcoded autoawq version in example notebooks

### ISSUE THREAD

**Issue by mtodisco10** [neuml/txtai#686]
I'm working through the [52_Build_RAG_pipleines_with_txtai colab](https://colab.research.google.com/github/neuml/txtai/blob/master/examples/52_Build_RAG_pipelines_with_txtai.ipynb) notebook and running into the below error when trying to  run `from txta.pipeline import LLM`
<img width="1129" alt="image" src="https://github.com/neuml/txtai/assets/13875567/a8637534-f32f-43ff-8feb-1e5e7a0fae05">

When I switch to a CPU it seems to work, but would like to use a GPU.  I'm seeing the same behavior when replicating on databricks with a GPU cluster.

Can you please advise?  Thanks.

**Comment by mtodisco10** [comment]
That's correct, I'm running directly through that Google Colab link.  I restarted the runtime session and I'm seeing the same error.

**Comment by davidmezzetti** [comment]
Thanks. I'll spin it up through Colab to see if I can reproduce the issue.

**Comment by davidmezzetti** [comment]
Just was able to take a look and the issue was hardcoding the autoawq version

The following change will fix the issue.

```
pip install git+https://github.com/neuml/txtai#egg=txtai[pipeline] autoawq
```

Though upgrading the package did require a `Restart session and Run all` as is common when upgrading certain packages in Colab.

I'll go through all the example notebooks and make this update as part of this issue. Thank you for reporting it!

**Comment by mtodisco10** [comment]
Thank you @davidmezzetti !
